#!/bin/bash

# botphIA Deployment Script for Render.com
# Version: 1.05
# Author: botphIA Team

set -e

echo "🚀 botphIA Deployment Script v1.05"
echo "=================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo -e "${RED}❌ Git is not installed. Please install git first.${NC}"
    exit 1
fi

# Check if we're in the right directory
if [ ! -f "botphia-render.yaml" ]; then
    echo -e "${RED}❌ botphia-render.yaml not found. Please run this script from the project root.${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Pre-checks passed${NC}"
echo ""

# Step 1: Initialize Git repository if needed
if [ ! -d ".git" ]; then
    echo "📁 Initializing Git repository..."
    git init
    git add .
    git commit -m "Initial commit - botphIA v1.05"
    echo -e "${GREEN}✅ Git repository initialized${NC}"
else
    echo -e "${YELLOW}ℹ️  Git repository already exists${NC}"
fi

# Step 2: Check for GitHub remote
echo ""
echo "🔗 GitHub Configuration"
echo "----------------------"

if git remote | grep -q "origin"; then
    REMOTE_URL=$(git remote get-url origin)
    echo -e "${GREEN}✅ Remote already configured: $REMOTE_URL${NC}"
else
    echo -e "${YELLOW}⚠️  No GitHub remote configured${NC}"
    echo ""
    read -p "Enter your GitHub username: " GITHUB_USER
    read -p "Enter repository name (default: botphia): " REPO_NAME
    REPO_NAME=${REPO_NAME:-botphia}
    
    GITHUB_URL="https://github.com/$GITHUB_USER/$REPO_NAME.git"
    
    echo ""
    echo "Adding remote: $GITHUB_URL"
    git remote add origin $GITHUB_URL
    echo -e "${GREEN}✅ GitHub remote added${NC}"
fi

# Step 3: Create/update production environment file
echo ""
echo "🔧 Updating Production Configuration"
echo "-----------------------------------"

# Update botphia/.env.production if frontend URL is provided
read -p "Enter your Render frontend URL (or press Enter to skip): " FRONTEND_URL
if [ ! -z "$FRONTEND_URL" ]; then
    # Extract base URL without https://
    BACKEND_URL=${FRONTEND_URL/botphia-web/botphia-api}
    WS_URL=${BACKEND_URL/https:/wss:}
    
    cat > botphia/.env.production << EOF
# Production environment variables for botphIA frontend
# Auto-generated by deploy.sh

# Backend API URL
VITE_API_URL=$BACKEND_URL

# WebSocket URL
VITE_WS_URL=$WS_URL/ws

# Environment
VITE_ENVIRONMENT=production
EOF
    
    echo -e "${GREEN}✅ Production URLs updated${NC}"
    git add botphia/.env.production
    git commit -m "Update production URLs for Render deployment" || true
fi

# Step 4: Push to GitHub
echo ""
echo "📤 Pushing to GitHub"
echo "-------------------"

read -p "Push to GitHub now? (y/n): " PUSH_CONFIRM
if [ "$PUSH_CONFIRM" = "y" ]; then
    git branch -M main
    git push -u origin main
    echo -e "${GREEN}✅ Code pushed to GitHub${NC}"
else
    echo -e "${YELLOW}ℹ️  Skipping GitHub push${NC}"
fi

# Step 5: Display next steps
echo ""
echo "🎯 Next Steps for Render.com"
echo "============================"
echo ""
echo "1. Go to https://render.com and sign in"
echo "2. Click 'New' → 'Blueprint'"
echo "3. Connect your GitHub repository"
echo "4. Select 'botphia-render.yaml' as blueprint file"
echo "5. Click 'Apply'"
echo ""
echo "6. After deployment, set these environment variables:"
echo "   - BINANCE_API_KEY (your Binance API key)"
echo "   - BINANCE_SECRET_KEY (your Binance secret)"
echo ""
echo "7. Create initial users:"
echo ""
echo "   curl -X POST https://botphia-api.onrender.com/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"email\": \"aurbaez@botphia.com\", \"password\": \"Profitz2025!\"}'"
echo ""
echo "   curl -X POST https://botphia-api.onrender.com/api/auth/register \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"email\": \"jalcazar@botphia.com\", \"password\": \"Profitz2025!\"}'"
echo ""
echo -e "${GREEN}🎉 Deployment preparation complete!${NC}"
echo ""
echo "📚 For detailed instructions, see: RENDER_DEPLOYMENT_GUIDE.md"