services:
  - type: worker
    name: trading-bot-v25
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main_trading_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"